README.md, charts/motel-child/Chart.lock, charts/motel-child/Chart.yaml, charts/motel-child/templates/victoria/vmagent.yaml, charts/motel-child/values.yaml, charts/motel-mothership/Chart.yaml, charts/motel-mothership/files/dashboards/opencost-cost-reporter-basic-overview.yaml, charts/motel-mothership/files/dashboards/opencost-cost-reporter-detailed-overview.yaml, charts/motel-mothership/templates/hmc/motel-child/flux-helm.yaml, charts/motel-mothership/templates/hmc/motel-child/svctmpl.yaml, charts/motel-mothership/templates/hmc/motel-regional/flux-helm.yaml, charts/motel-mothership/templates/hmc/motel-regional/svctmpl.yaml, charts/motel-regional/Chart.lock, charts/motel-regional/Chart.yaml, charts/motel-regional/files/dashboards/opencost-cost-reporter-basic-overview.yaml, charts/motel-regional/files/dashboards/opencost-cost-reporter-detailed-overview.yaml, charts/motel-regional/values.yaml, demo/cluster/aws-child.yaml, demo/cluster/aws-regional.yaml
Optional availability to enable [external-dns](https://kubernetes-sigs.github.io/external-dns/) service to automatically manage ingress hostnames.
Close https://github.com/Mirantis/motel/issues/7
Close https://github.com/Mirantis/hmc/issues/735
=> Add external-dns and opencost helm charts

charts/kof-collectors/templates/opentelemetry/instrumentation.yaml, charts/kof-collectors/templates/opentelemetry/node-collector.yaml, charts/kof-collectors/values.yaml, charts/kof-operators/templates/opentelemetry/clusterroles/opentelemetry-operator-manager.yaml, charts/kof-operators/values.yaml, charts/kof-storage/templates/grafana/grafana.yaml, charts/kof-storage/values.yaml
Closes https://github.com/K0rdent/kof/issues/6
hmc-controller autoinstrumentation doesn't work as the [fix](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/1471) for net library is unreleased yet
https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/CHANGELOG.md
=> Add opentelemetry autoinstrumentation example of go program for grafana

demo/demo-mothership-values.yaml
This fixes a problem in the demo values where hmc wasn’t renamed to kcm, which was stopping ServiceTemplates from being created.
=> Fix kcm value in helm chart demo values

Makefile, charts/kof-mothership/Chart.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/Chart.lock
This reverts commit ea983ea9d6dbe49c21968b6af13c26021d03ec3e from https://github.com/k0rdent/kof/pull/31 because:
[WARNING] `templates/sveltos/copy-secrets-cluster-profile.yaml`: object name does not conform to Kubernetes naming requirements: `"kofStorageSecrets": metadata.name: Invalid value: "kofStorageSecrets"`: a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. example.com, regex used for validation is `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`)
=> Revert "Applied helm values naming convention"

charts/kof-mothership/Chart.yaml, charts/kof-mothership/files/dashboards/kubernetes-views-global.yaml, charts/kof-mothership/files/dashboards/kubernetes-views-namespaces.yaml
Part of https://github.com/k0rdent/kof/issues/11
Set `panels[].fieldConfig.defaults.noValue: "None, that's good"`
where `panels[].description: "No data is generally a good thing here."`
=> Replaced some "No data" with "None, that's good" based on description

charts/kof-mothership/templates/k0rdent/catalog/ingress-nginx.yaml, charts/kof-mothership/templates/promxy/_helpers.tpl, charts/kof-mothership/templates/promxy/ingress.yaml, charts/kof-mothership/templates/promxy/operator-deployment.yaml, charts/kof-mothership/templates/promxy/promxy-config.yaml, charts/kof-mothership/templates/promxy/promxy-deployment.yaml, charts/kof-mothership/templates/promxy/role.yaml, charts/kof-mothership/templates/promxy/role_binding.yaml, charts/kof-mothership/templates/promxy/service.yaml, charts/kof-mothership/templates/promxy/serviceaccount.yaml, charts/kof-mothership/templates/sveltos/service-monitors.yaml, demo/cluster/aws-standalone-managed.yaml, demo/cluster/aws-standalone-storage.yaml
Related to https://github.com/k0rdent/docs/pull/94 and https://github.com/k0rdent/docs/issues/92
* **Before** the fix:
* **[Official docs draft](https://github.com/k0rdent/docs/blob/2dce80fcbc28f794b264e69661139a417480e417/docs/kof.md#management-cluster)** of `kof-mothership` had to explain this "known issue":  
"All pods should be `Running` except the `kof-mothership-promxy`:  
it is waiting for `kof-mothership-promxy-config` secret  
that will be auto-created and updated by `kof-mothership-promxy-operator`  
on deployment of storage clusters below."
* **After** the fix:
```
make helm-push
make dev-ms-deploy-cloud
REVISION: 4
kubectl get pod -A | grep promxy
kof                  kof-mothership-promxy-5f8bbc8469-zbg74                         2/2     Running   0          4m51s
kof …
```
=> Run, promxy, run! Bonus: support of kcm 0.1.0

charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-storage/templates/grafana/grafana.yaml, docs/DEV.md
1. Fix readme as all repos dependencies have to be updated before installing any chart.
2. Removed plugins loader due to officially supported: https://grafana.com/grafana/plugins/all-plugins/?search=victoria
=> Removed grafana plugins loader as it's now officially supported

demo/cluster/aws-eks-managed.yaml, demo/cluster/aws-eks-storage.yaml, demo/cluster/aws-standalone-managed.yaml, demo/cluster/aws-standalone-storage.yaml
```
KUBECONFIG=dev/aws-standalone-managed-kubeconfig helm list -A --pending
NAME        	NAMESPACE	REVISION	UPDATED                                	STATUS         	CHART              	APP VERSION
cert-manager	kof      	17      	2025-02-04 13:41:25.528868884 +0000 UTC	pending-install	cert-manager-1.16.2	1.16.2     
KUBECONFIG=dev/aws-standalone-managed-kubeconfig kubectl logs -n kof cert-manager-startupapicheck-g992k
I0204 13:49:04.423461       1 api.go:103] "Not ready" logger="cert-manager.startupapicheck.checkAPI"
err="the cert-manager CRDs are not yet installed on the Kubernetes API server"
underlyingError="error finding the scope of the object: failed to get restmapping:
no matches for kind \"CertificateRequest\" in version \"cert-manager.io/v1\"" …
```
=> Update service values as catalog charts are wrappers of upstream charts

charts/kof-collectors/templates/opentelemetry/node-collector.yaml
We cannot guarantee that all data processed is correct, so we have to drop on errors
=> Fix node collector crash due to unhandled error

.github/workflows/release_charts.yml, charts/kof-mothership/values.yaml
* Full file for review: https://github.com/k0rdent/kof/blob/72027b8b9f39940cd88941c6a7083dd7f92366de/.github/workflows/release_charts.yml
* Test log: https://github.com/denis-ryzhkov/kof/actions/runs/13177382113/job/36779795450
* Check of pushed charts:
```
helm pull oci://ghcr.io/denis-ryzhkov/kof/charts/kof-operators:0.1.0-oci-test
Pulled: ghcr.io/denis-ryzhkov/kof/charts/kof-operators:0.1.0-oci-test
Digest: sha256:41b9fccb63ce80970393b802dc8480c76bdaeee8a7773ac05db714f1a51da4a1
tar zxf kof-operators-0.1.0-oci-test.tgz 
cat kof-operators/Chart.yaml
apiVersion: v2
appVersion: 0.1.0-oci-test
dependencies:
- condition: opentelemetry-operator.enabled
name: opentelemetry-operator
repository: https://open-telemetry.github.io/opentelemetry-helm-charts
version: 0.75.*
- condition: …
```
=> Build and push kof helm charts to oci://ghcr.io/k0rdent/kof/charts

charts/kof-mothership/templates/k0rdent/catalog/_helpers.tpl, charts/kof-mothership/templates/k0rdent/catalog/cert-manager.yaml, charts/kof-mothership/templates/k0rdent/catalog/ingress-nginx.yaml
Part of https://github.com/k0rdent/kof/issues/60
* We had our own service templates for `cert-manager` and `ingress-nginx`
because at some point they were moved from `kcm` to `k0rdent/catalog`.
* Now they're installed with `kcm` again, so `kof-mothership` installation fails.
```
helm install -f mothership-values.yaml -n kof kof-mothership \
oci://ghcr.io/k0rdent/kof/charts/kof-mothership --version 0.1.0
Pulled: ghcr.io/k0rdent/kof/charts/kof-mothership:0.1.0
Digest: sha256:35baa81751027d1a6fd38ce229d04b220e1999a824021a5672cf72c252e203f4
Error: INSTALLATION FAILED: Unable to continue with install:
ServiceTemplate "cert-manager-1-16-2" in namespace "kcm-system" exists
and cannot be imported into the current release:
invalid ownership metadata; annotation validation error:
key …
```
=> Use-or-create service templates kof depends on

charts/kof-mothership/values.yaml, charts/kof-storage/values.yaml
* Closes https://github.com/k0rdent/kof/issues/83
* Related to https://github.com/k0rdent/docs/pull/73
* Based on https://github.com/VictoriaMetrics/helm-charts/blob/ab4b3d4b5c3286f2c1484acc19c2366a1bc4e6e6/charts/victoria-metrics-operator/values.yaml#L39-L41
* Tests:
```
helm uninstall --wait --cascade foreground -n kof kof-mothership
These resources were kept due to the resource policy:
[ServiceTemplate] cert-manager-1-16-2
[ServiceTemplate] ingress-nginx-4-11-3
release "kof-mothership" uninstalled
kubectl get job -n kof
NAME                                                    STATUS     COMPLETIONS   DURATION   AGE
kof-mothership-victoria-metrics-operator-cleanup-hook   Complete   1/1           25s        5m43s
kubectl get pods -n kof …
```
=> Fixed uninstallation, now VM objects are deleted

.github/workflows/helm-docs.yaml, .pre-commit-config.yaml, charts/kof-mothership/README.md, charts/kof-mothership/README.md.gotmpl, charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-mothership/templates/promxy/_helpers.tpl, charts/kof-mothership/templates/promxy/role.yaml, charts/kof-mothership/templates/promxy/role_binding.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/Chart.lock, demo/demo-mothership-values.yaml
Shaun has suggested - https://github.com/k0rdent/olddocs/issues/92#issuecomment-2647585965
> The values options for the mothership template are unclear without going looking through the templates themselves
This PR adds the [helm-docs](https://github.com/norwoodj/helm-docs) for `kof-mothership` chart values and the `pre-commit` hook.
Rendered markdown:  
https://github.com/k0rdent/kof/blob/3348e33107a4ae97e9655e28e3091e0da753d485/charts/kof-mothership/README.md
Open source suggestion: https://github.com/norwoodj/helm-docs/pull/106#issuecomment-2659793069
Also fixed few minor issues, see the diff.
=> helm-docs for kof-mothership values

charts/kof-mothership/templates/k0rdent/kof/svctmpl.yaml, charts/kof-mothership/templates/sveltos/child-cluster-profile.yaml, docs/DEV.md
Closes https://github.com/k0rdent/kof/issues/107
* Replaced `kof-child-cluster` `ClusterProfile` added in https://github.com/k0rdent/kof/pull/101
with a `MultiClusterService`.
* Found we cannot replace [copy-secrets-cluster-profile](https://github.com/k0rdent/kof/blob/198b370231a8e7c117b95a8ad5fd95658f04f49c/charts/kof-mothership/templates/sveltos/copy-secrets-cluster-profile.yaml)
because [MultiClusterService supports](https://github.com/k0rdent/kcm/blob/39e7480ae7a02bb06b07b6d752a2e651f8ddc8ff/api/v1alpha1/multiclusterservice_types.go#L124-L129) just `clusterSelector` and `serviceSpec`,
while we also need `templateResourceRefs` and `policyRefs` in this case.
* We may replace this `ClusterProfile` with the upcoming `kof-operator` later if needed.
* Verified there are no other …
=> Replaced `kof-child-cluster` ClusterProfile with a MultiClusterService

charts/kof-mothership/templates/k0rdent/catalog/_helpers.tpl, charts/kof-mothership/templates/k0rdent/kof/helm-repo.yaml, charts/kof-mothership/templates/k0rdent/kof/wait-valid-svctmpl.yaml, docs/DEV.md
Part of https://github.com/k0rdent/kof/issues/107
This PR fixes the `not found` in https://github.com/k0rdent/kof/actions/runs/13584319097/job/37975900948
related to https://github.com/k0rdent/kof/pull/120
After the fix it failed with another error - `the template is not valid`:
https://github.com/k0rdent/kof/actions/runs/13587191647/job/37984685820?pr=121
This happens because the `ServiceTemplate` needs some time to get `VALID` status,
can be checked with `kubectl get svctmpl -A`
I've asked to add auto-retry to `MultiClusterService`,
and added a pre-install helm hook to wait for `VALID` in this PR.
Now it fails with `HelmRepository not found`:
https://github.com/k0rdent/kof/actions/runs/13588099907/job/37987516531?pr=121
Fixing in the same way and testing: …
=> Fix of `validation.multiclusterservice: ServiceTemplate cert-manager-1-16-2 not found`

kof-operator/internal/controller/clusterdeployment_controller_test.go, kof-operator/internal/controller/clusterdeployment_kof_cluster_role.go
* Part of istio: https://github.com/k0rdent/kof/issues/94
=> Added `regional_cluster_name` to child cluster `ConfigMap` to support istio

charts/kof-collectors/templates/_helpers.tpl, charts/kof-collectors/templates/opentelemetry/collector.yaml, charts/kof-collectors/templates/opentelemetry/node-collector.yaml
1. add a helper
2. if an endpoint scheme is http: add tls.insecure = true
3. otherwise add tls_options if any
=> support passing and detecting tls options for collectors

Makefile, demo/cluster/aws-eks-child.yaml, demo/cluster/aws-eks-regional.yaml, demo/cluster/aws-standalone-child.yaml, demo/cluster/aws-standalone-istio-child.yaml, demo/cluster/aws-standalone-regional.yaml, kof-operator/internal/controller/clusterdeployment_config.go, kof-operator/internal/controller/clusterdeployment_controller.go, kof-operator/internal/controller/clusterdeployment_controller_test.go, kof-operator/internal/controller/clusterdeployment_kof_cluster_role.go
* Part of https://github.com/k0rdent/kof/issues/70
* Improvement of https://github.com/k0rdent/kof/pull/130
* Auto-discover regional cluster using AWS region, Azure location, etc - when child `ClusterDeployment` has no `kof-regional-cluster-name` label.
* Note this label may still be useful e.g. when there are multiple isolated apps in the same region and the same management cluster.
* Tested end-to-end.
* Proofs:
```
kubectl get clusterdeployment -n kcm-system dryzhkov-aws-standalone-child -o yaml | yq .metadata.labels
k0rdent.mirantis.com/component: kcm
k0rdent.mirantis.com/kof-cluster-role: child
k0rdent.mirantis.com/kof-storage-secrets: "true"
kubectl get clusterdeployment -n kcm-system dryzhkov-aws-standalone-child -o yaml | yq .spec.config.region
us-west-1
kubectl get …
```
=> Auto-discover regional cluster using AWS region, Azure location, etc

.github/workflows/pr_test_helm_chart.yml, Makefile
* Part of https://github.com/k0rdent/docs/issues/148
* Error after bump of `KIND_VERSION` in https://github.com/k0rdent/kcm/pull/1272 is:
```
make dev-ms-deploy
...
bin/kind-v0.23.0 load docker-image kof-operator-controller --name kcm-dev
Image: "kof-operator-controller" with ID "sha256:REDACTED"
not yet present on node "kcm-dev-control-plane", loading...
ERROR: failed to detect containerd snapshotter
```
* Apply this PR and then update your existing kof repo:
```
rm bin/kind*
make kind
Downloading sigs.k8s.io/kind@v0.27.0
make dev-ms-deploy
...
bin/kind-v0.27.0 load docker-image kof-operator-controller --name kcm-dev
Image: "kof-operator-controller" with ID "sha256:REDACTED"
not yet present on node "kcm-dev-control-plane", loading...
cp -f charts/kof-mothership/values.yaml …
```
=> Bump kind version for compatibility with kcm

charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-mothership/templates/sveltos/regional-multi-cluster-service.yaml, charts/kof-storage/templates/grafana/grafana.yaml, charts/kof-storage/templates/jaeger/ingress.yaml, charts/kof-storage/templates/victoria/vmauth.yaml, demo/cluster/aws-standalone-child.yaml, demo/cluster/aws-standalone-istio-child.yaml, demo/cluster/aws-standalone-istio-regional.yaml, demo/cluster/aws-standalone-regional.yaml
* Part of https://github.com/k0rdent/docs/issues/148
* Creating a new annotation for every possible custom value is not a scalable option,
so we decided to create generic patch annotations. The first one:
```
k0rdent.mirantis.com/kof-storage-values: |
victoria-logs-single:
server:
replicaCount: 2
```
* Tested:
```
KUBECONFIG=dev/regional-kubeconfig helm get values -n kof kof-storage
USER-SUPPLIED VALUES:
cert-manager:
email: denisr@denisr.com
external-dns:
enabled: true
global:
storageClass: ""
grafana:
ingress:
host: grafana.dryzhkov-aws-standalone-regional.REDACTED
security:
credentials_secret_name: grafana-admin-credentials
jaeger:
ingress:
enabled: true
host: jaeger.dryzhkov-aws-standalone-regional.REDACTED
tmp: ""
victoria-logs-single:
server:
persistentVolume:
storageClassName: "" …
```
=> Patch of values via annotation

Makefile
YQ should be used from cli-install command, not assume it's globally available
```
/bin/sh: yq: command not found
Image: "kof-operator-controller:v" with ID "sha256:d1dd70dac2901d902c33f276315c51edb0395aa84f416bb9940145a545893cbe" not yet present on node "kcm-dev-control-plane", loading...
```
=> Fix yq usage in makefile

charts/kof-mothership/templates/k0rdent/catalog/_helpers.tpl, charts/kof-mothership/templates/k0rdent/kof/svctmpl.yaml
pre-upgrade hook cannot be used for service templates as it will be deleted on next upgrade due to default
https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies annotation.
It causes
```
W0327 16:59:21.424244    8730 warnings.go:70] The kof-storage-0-2-0-rc2 ServiceTemplate object can't be removed if MultiClusterService objects [kof-regional-cluster] referencing it still exist
Error: UPGRADE FAILED: pre-upgrade hooks failed: admission webhook "validation.servicetemplate.k0rdent.mirantis.com" denied the request: template deletion is forbidden
```
=> Remove pre-upgrade hook from service templates

Makefile
Sometimes it is handy to have a local repo for local sandboxes. It will be plain-text by default, so let's keep it like that and allow a user to specify it.
=> Support plain-text local BYOT OCI Repo

charts/kof-child/templates/child-multi-cluster-service.yaml, charts/kof-child/values.yaml, charts/kof-istio/templates/kof-child-cluster-profile.yaml, charts/kof-istio/templates/kof-regional-cluster-profile.yaml, charts/kof-istio/values.yaml, charts/kof-regional/templates/regional-multi-cluster-service.yaml, charts/kof-regional/values.yaml
Part of https://github.com/k0rdent/kof/issues/180
This allow to specify values for collector and storage helm charts that passed to ClusterProfiles (i.e. applied to all clusters)
=> Add values to override for child and regional cluster profiles

Makefile, charts/kof-child/Chart.yaml, charts/kof-child/templates/child-multi-cluster-service.yaml, charts/kof-collectors/Chart.yaml, charts/kof-istio/Chart.yaml, charts/kof-istio/templates/child-cluster-profiles.yaml, charts/kof-istio/templates/kof-child-cluster-profile.yaml, charts/kof-istio/templates/kof-regional-cluster-profile.yaml, charts/kof-istio/values.yaml, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md, charts/kof-mothership/values.yaml, charts/kof-operators/Chart.yaml, charts/kof-regional/Chart.yaml, charts/kof-regional/templates/regional-multi-cluster-service.yaml, charts/kof-storage/Chart.yaml, docs/DEV.md
* Installing `kof-istio` before `kof-mothership` - no need to delete all kof pods now.
* Adapted repo-related values of `kof-istio` to recent `repo.spec` change.
* Fixed waiting for `VALID` status in `make dev-ms-deploy`.
* Fixed `Spec is immutable` on upgrade due to migration to `kgst` by creating ServiceTemplate `cert-manager-1-16-4`.
* Tested on AWS and Azure with and without `kof-istio`.
=> fix: Few fixes for kof v0.2.1

charts/kof-child/templates/child-multi-cluster-service.yaml, charts/kof-collectors/values.yaml, charts/kof-istio/templates/_helpers.tpl, charts/kof-istio/templates/kof-child-cluster-profile.yaml, charts/kof-istio/templates/kof-regional-cluster-profile.yaml, charts/kof-regional/templates/regional-multi-cluster-service.yaml, charts/kof-regional/values.yaml
* Part of https://github.com/k0rdent/kof/issues/112
* Added `kof-operators` and `kof-collectors` to `kof-regional` MCS
and to `kof-istio` regional ClusterProfile.
* Deleted redundant values (equal to default `values.yaml`) from all MCS.
* Fixed two default values in `kof-collectors`:
`.kof.logs.endpoint` and `.opencost.opencost.prometheus.external.url`.
* Simplified Sveltos-in-Helm multiline templates with unified open/close tags:
```
{{`{{`}}
...
{{`}}`}}
```
* Renamed `$values $collectorsValues $patch`
to `$collectorsValuesHere $collectorsValuesFromHelm $collectorsValuesFromAnnotation`
and `$storageValuesHere $storageValuesFromHelm $storageValuesFromAnnotation`,
to avoid confusion.
* DRY-ed collectors values in both istio ClusterProfiles, checked result, OK:
```
kubectl get …
```
=> feat: Collect data from regional clusters too

charts/kof-collectors/templates/opentelemetry/collector.yaml, charts/kof-collectors/templates/opentelemetry/node-collector.yaml
Example of passing env variables via kof-collectors values:
```
collectors:
node:
env:
- name: AWS_ACCESS_KEY_ID
valueFrom:
secretKeyRef:
name: aws-credentials
key: AWS_ACCESS_KEY_ID
```
=> feat: add collectors env variables values

Makefile, charts/kof-collectors/templates/_helpers.tpl, docs/DEV.md, docs/collect-from-management.md, docs/release.md
* Part of https://github.com/k0rdent/kof/issues/112
* Documented 4 options to collect data from DEV management cluster.
* Deleted redundant custom values from `make dev-collectors-deploy` and similar.
* Fixed "Waiting for service templates to become VALID" on upgrade when old versions are still there.
* Allowed to disable default exporters by specifying empty endpoints.
* Tested each option, OK.
=> feat: Documented 4 options to collect data from DEV management cluster

charts/kof-storage/templates/jaeger/ingress.yaml, charts/kof-storage/templates/jaeger/secret.yaml, charts/kof-storage/values.yaml, docs/DEV.md
* Closes https://github.com/k0rdent/kof/issues/212
* Tested:
```
curl -v https://jaeger.dryzhkov-aws-standalone-regional.REDACTED/
< HTTP/2 401
...
<head><title>401 Authorization Required</title></head>
```
* Logged in. It shows data, OK.
=> fix: Protect Jaeger UI

charts/kof-mothership/templates/kof-operator/role.yaml, kof-operator/internal/controller/clusterdeployment_controller.go, kof-operator/internal/controller/clusterdeployment_kof_cluster_role.go, kof-operator/internal/controller/promxyservergroup_controller.go
- Add patch events permission to kof-operator
- Add RegionalClusterDiscoveryFailed event
- Removed RequeueInterval due to warning below
```
INFO    Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes requeuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler
```
=> fix: add RegionalClusterDiscoveryFailed event

charts/kof-mothership/templates/k0rdent/kof/svctmpl.yaml
* https://github.com/k0rdent/kof/pull/234 had a wrong assumption, this PR fixes it.
=> fix: Return ServiceTemplate `kof-istio-0-2-1` - it is used in ClusterProfile

demo/cluster/aws-standalone-istio-regional.yaml
* Part of https://github.com/k0rdent/kof/issues/229
* Updated istio-child workers to use `t3.medium` instead `t3.small` in https://github.com/k0rdent/docs/pull/224 - this fixed the issue for the **child** cluster.
* Updated istio-**regional** workers to use `t3.xlarge` as even `t3.large` was not enough, leading to:
```
vminsert-cluster,
kof-collectors-node-exporter-targetallocator:
1 node(s) had untolerated taint {node-role.kubernetes.io/master: },
3 Insufficient cpu.
preemption: 0/4 nodes are available
```
* This fix resolved the issue.
=> fix: "Insufficient cpu" for istio-regional

charts/kof-mothership/templates/victoria/service-monitors.yaml, docs/DEV.md, kof-operator/go.mod, kof-operator/go.sum
* Part of https://github.com/k0rdent/kof/issues/232
* Added ServiceMonitor for alertmanager.
* Tested: "Grafana - Explore" started showing metrics like `alertmanager_alerts`
* Also fixed dev docs typo and https://github.com/k0rdent/kof/security/dependabot/13
=> feat: Added ServiceMonitor for alertmanager

.github/workflows/triage.yaml
* When we add `triage-ok` and `enhancement` labels, two `triage` CI jobs are started.
* Both jobs see `needs-triage` label exists, so both jobs start the `actions/github-script`.
* First job deletes `needs-triage` successfully: https://github.com/k0rdent/kof/actions/runs/14638817106/job/41076130740
* Second job may fail with `Label does not exist`: https://github.com/k0rdent/kof/actions/runs/14638817112/job/41076130747
* As a result maintainers of the repo receive emails with errors that are not errors actually.
* This PR silences the case when `Label does not exist` already.
=> fix: `Label does not exist` on `removeLabel` when multiple triage CI jobs are triggered

charts/kof-mothership/files/dashboards/nvidia-dcgm-exporter.yaml
This PR introduces a Grafana dashboard for monitoring NVIDIA GPU metrics via the DCGM Exporter. 
The dashboard is based on the official [NVIDIA dcgm-exporter](https://github.com/NVIDIA/dcgm-exporter/blob/main/grafana/dcgm-exporter-dashboard.json) with few additional template key inherited from other existing dashboards in the repo.
The dashboard assumes that the DCGM Exporter metrics are being scraped. This requires a ServiceMonitor resource to be present, which directs to the DCGM Exporter's metrics endpoint.
Note - While the NVIDIA GPU Operator deploys the DCGM Exporter, it does not, by default, create a ServiceMonitor resource for it.
=> feat: add nvidia gpu monitoring dashboard to grafana

.github/workflows/pr_test_upgrade.yml
KCM upgrade testing isn't in scope of KOF.
Simplified dev deploy doesn't work, so removing it for now.
=> chore: remove KCM upgrade from KOF upgrade test

charts/kof-collectors/templates/_helpers.tpl, charts/kof-collectors/templates/opentelemetry/exporters/kube-api-server/servicemonitor.yaml, charts/kof-collectors/values.yaml, charts/kof-operators/values.yaml
- Move kubernetes-api metrics collection to a service monitor
- Removed prometheus receiver from cluster collector
=> feat: adopting kube-api-server service monitor from opentelemetry-kube-stack

.github/workflows/release_operator.yml
Bump go version to prevent CI falure due outdated version
=> chore: bump go version to upcomming upgrade

demo/cluster/aws-standalone-regional.yaml, kof-operator/api/v1beta1/groupversion_info.go, kof-operator/internal/controller/clusterdeployment_controller_test.go, kof-operator/internal/controller/clusterdeployment_kof_cluster_role.go, kof-operator/internal/controller/promxyservergroup_controller_test.go
Closes https://github.com/k0rdent/kof/issues/258
Added  clusterDeployment annotation to customize promxy and grafana datasource http config params
```yaml
k0rdent.mirantis.com/kof-http-config: '{"dial_timeout": "10s", "tls_config": {"insecure_skip_verify": true}}'
```
=> feat: add cluster annotation to customize promxy and datasource http config

.github/workflows/release_charts.yml
* Debugging https://github.com/k0rdent/kof/actions/runs/15063991323/job/42344618175
* The `-x` will show where exactly the error happens, because locally it looks good:
```
+ helm repo add prometheus-node-exporter https://prometheus-community.github.io/helm-charts
"prometheus-node-exporter" already exists with the same configuration, skipping
+ helm repo add kube-state-metrics https://prometheus-community.github.io/helm-charts
"kube-state-metrics" already exists with the same configuration, skipping
+ helm repo add opencost https://opencost.github.io/opencost-helm-chart
"opencost" already exists with the same configuration, skipping
+ helm repo add cert-manager-istio-csr https://charts.jetstack.io
"cert-manager-istio-csr" already exists with the same configuration, skipping
+ helm repo …
```
=> test: Debug `"helm repo add" requires 2 arguments` in `workflows/release_charts`

.github/workflows/release_charts.yml
* https://github.com/k0rdent/kof/pull/280
* https://github.com/k0rdent/kof/pull/281
* Found yq version has changed and now behaves differently:
```
yq --version
yq (https://github.com/mikefarah/yq/) version v4.45.4
echo '{"a": ["c", "d"]}' | yq '.a[] | "b" + .' 
bc
bd
echo '{"a": ["c"]}' | yq '.a[] | "b" + .' 
bc
echo '{"a": []}' | yq '.a[] | "b" + .' 
b
echo '{"a": []}' | yq '.a | map("b" + .)[]'
echo '{"a": ["c", "d"]}' | yq '.a | map("b" + .)[]'
bc
bd
```
* Found yq has fixed the [issue](https://github.com/mikefarah/yq/issues/) 2359 (not referencing it directly to avoid spam) which exposed a bug in our yq query.
* Fixed, Tested with local yq v4.45.4 and in fork, OK: https://github.com/denis-ryzhkov/kof/actions/runs/15069511632/job/42362050446#step:6:21
=> fix: `"helm repo add" requires 2 arguments` in `workflows/release_charts` exposed by fix in yq v4.45.4

charts/kof-collectors/templates/kcm/service-monitor/kcm-controller-manager.yaml
kcm produces some invalid projectsveltos_* metrics due to some import in golang,
this commit is a workaround for 
https://github.com/k0rdent/kcm/issues/1549
=> fix: filter out projectsveltos_* metrics from kcm cm

kof-operator/webapp/collector/package-lock.json, kof-operator/webapp/collector/package.json
=> chore: bump `vite` from 6.2.0 to 6.2.7

charts/kof-mothership/templates/prometheus/rules/k8s.rules.container_cpu_usage_seconds_total.yaml, charts/kof-mothership/templates/prometheus/rules/k8s.rules.container_memory_cache.yaml, charts/kof-mothership/templates/prometheus/rules/k8s.rules.container_memory_rss.yaml, charts/kof-mothership/templates/prometheus/rules/k8s.rules.container_memory_swap.yaml, charts/kof-mothership/templates/prometheus/rules/k8s.rules.container_memory_working_set_bytes.yaml, charts/kof-mothership/templates/prometheus/rules/kubelet.rules.yaml, charts/kof-mothership/templates/prometheus/rules/kubernetes-resources.yaml, charts/kof-mothership/templates/prometheus/rules/kubernetes-storage.yaml, charts/kof-mothership/templates/prometheus/rules/kubernetes-system-kubelet.yaml, charts/kof-mothership/templates/prometheus/rules/node-exporter.rules.yaml, charts/kof-mothership/templates/prometheus/rules/node-exporter.yaml, charts/kof-mothership/templates/prometheus/rules/node-network.yaml, charts/kof-mothership/templates/prometheus/rules/node.rules.yaml
* Part of https://github.com/k0rdent/docs/issues/375 caused by https://github.com/k0rdent/kof/issues/242
* Related PRs: https://github.com/k0rdent/kof/pull/248 and https://github.com/k0rdent/docs/pull/397
* Found the new `CPUThrottlingHigh` alert doesn't work against current metrics,
because [new alert queries](https://github.com/k0rdent/kof/blob/332f66ff03bae8abd37cc7e754dd8d7a42d059a7/charts/kof-mothership/templates/prometheus/rules/kubernetes-resources.yaml#L263-L265)
`container_cpu_cfs_periods_total{job="kubelet", metrics_path="/metrics/cadvisor"}`,
while current metrics data `group by (job, metrics_path) (container_cpu_cfs_periods_total)` shows
`{job="integrations/kubernetes/cadvisor"}`
* The new metrics collectors PR https://github.com/k0rdent/kof/pull/273 is not ready yet and is …
=> fix: Temporary adaptation of new alerts to current metrics

charts/kof-collectors/Chart.lock, charts/kof-collectors/Chart.yaml, charts/kof-mothership/Chart.lock, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md, charts/kof-operators/Chart.lock, charts/kof-operators/Chart.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/Chart.yaml
Align all chart versions across kof charts.
Get rid of any wildcard versions (due to possible ambiguity when rebuilding charts).
`sveltos-dashboard` chart is bumped to 0.54.0 to match all the rest sveltos components in the system.
> [!NOTE]
> This is PR to `v1.0.0` release branch. I will prepare a separate PR to main after this one will be merged.
> [!NOTE]
> I didn't bumped chart version themselves, not sure if it is required or not. If yes I will adjust PR
=> chore: align chart versions; sveltos dashboard bump to 0.54.0

Makefile, charts/kof-collectors/values.yaml, charts/kof-mothership/Chart.lock, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md, charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-mothership/templates/promxy/promxy-deployment.yaml, charts/kof-mothership/templates/victoria/vmalert.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/Chart.yaml, charts/kof-storage/templates/grafana/grafana.yaml, charts/kof-storage/templates/jaeger/jaeger.yaml, charts/kof-storage/templates/victoria/vmalert.yaml, charts/kof-storage/values.yaml, docs/DEV.md
* Part of https://github.com/k0rdent/kof/issues/315
* Run after upgrade to [grafana-operator v5.16.0](https://github.com/grafana/grafana-operator/releases/tag/v5.16.0):
```bash
kubectl apply --server-side --force-conflicts -f https://github.com/grafana/grafana-operator/releases/download/v5.16.0/crds.yaml
```
for management cluster and for each regional cluster via `KUBECONFIG=regional-kubeconfig kubectl` from [here](https://docs.k0rdent.io/next/admin/kof/kof-verification/#verification-steps).
* Values to set in kof charts:
* `global.registry`
* `global.image.registry` - for VictoriaMetrics [here](https://github.com/VictoriaMetrics/helm-charts/blob/f601e33f4059bb6fd14791be9dd0bf8fa3339002/charts/victoria-metrics-common/templates/_image.tpl#L54).
* `cluster-api-visualizer.image.repository` …
=> feat: Custom image repos for Grafana and others

Makefile, charts/kof-collectors/templates/opentelemetry/node-collector.yaml, charts/kof-collectors/values.yaml, charts/kof-mothership/README.md, charts/kof-mothership/templates/kof-operator/operator-deployment.yaml, charts/kof-mothership/templates/promxy/promxy-deployment.yaml, charts/kof-mothership/templates/victoria/vmalertmanager.yaml, charts/kof-mothership/values.yaml, charts/kof-operators/values.yaml, charts/kof-storage/templates/victoria/vmalert.yaml, charts/kof-storage/templates/victoria/vmcluster.yaml, charts/kof-storage/values.yaml
* Part of https://github.com/k0rdent/kof/issues/315
* Based on https://github.com/k0rdent/kof/pull/322
- charts/kof-collectors/values.yaml `global.imageRegistry`
- charts/kof-mothership/values.yaml `global.registry`
- charts/kof-operators/values.yaml `opentelemetry-operator.manager.image.repository`
- charts/kof-operators/values.yaml `opentelemetry-operator.kubeRBACProxy.image.repository`
- charts/kof-storage/values.yaml `global.image.registry`
* Fixes on debug:
* `sveltos-dashboard` [expects](https://github.com/projectsveltos/helm-charts/blob/sveltos-dashboard-0.54.0/charts/dashboard/templates/deployment.yaml#L46) non-empty [global.registry](https://github.com/projectsveltos/helm-charts/blob/sveltos-dashboard-0.54.0/charts/dashboard/values.yaml#L2),
leading to `couldn't parse image name …
=> feat: Custom image registries part 2

charts/kof-child/templates/child-multi-cluster-service.yaml
kof controller generates CMs in the same namespace as child cluster however, the templates expect the CM in the KCM namespace, which is incorrect
closes #262
=> fix: use correct namespace name for MCS

charts/kof-mothership/templates/grafana/grafana.yaml
* Part of https://github.com/k0rdent/kof/issues/315
* Caused by merge https://github.com/k0rdent/kof/pull/348
=> fix: Duplicate `version` field in Grafana

.github/workflows/release_operator.yml
* CI `kof-operator-release` https://github.com/k0rdent/kof/actions/runs/15870213164/job/44744835120
failed with:
```
webapp/collector/webapp.go:9:12: pattern dist: no matching files found
```
* This PR tries to fix this bug.
=> fix: `pattern dist` not found on `kof-operator-release`

charts/kof-mothership/Chart.lock, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md
* Why: https://github.com/k0rdent/catalog/issues/468#issuecomment-3004582639
=> fix: Switching to kgst 0.2.0 to use k0rdent v1beta1 instead of deleted v1alpha1

.github/workflows/pr_test_upgrade.yml, Makefile, config/support-bundle.yaml, demo/cluster/adopted-cluster-child.yaml, demo/cluster/adopted-cluster-regional.yaml
Closes https://github.com/k0rdent/kof/issues/352
- Cleanup kind clusters and cluster deployment if any deployed from the previous CI execution
- Create a support-bundle artifact archive with custom resources and logs if CI fails for troubleshooting
=> test: add support bundle to troubleshoot CI issues

Makefile, charts/kof-child/values.yaml, charts/kof-mothership/README.md, charts/kof-mothership/values.yaml, charts/kof-regional/values.yaml
* Part of https://github.com/k0rdent/kof/issues/399
* Values workaround for kof release 1.1.0 will be added to the docs.
=> fix: Added letter `v` to `cert-manager:v1.16.4` for compatibility with all registries

charts/kof-mothership/templates/prometheus/rules/alertmanager.rules.yaml
partially closes #407 
we user vmalertmanager from vmcluster, job name should be different
=> fix: patch up incorrect alertmanager rules job label variable

charts/kof-collectors/values.yaml
events processor that casts event assumes that scope field is nonempty and contains receiver name, but with k8sobjects this is not the case so we resort to another heuristic on detecting that events processors should be applied based on k8s.resource.name
=> fix: k8s events processor

charts/kof-collectors/values.yaml
related to #412 
1. add serviceMonitor for TA
2. add prom labels for UI for other prom rcvrs
note: added metrics: "host:port" stanza, seemingly a bug in the operator, it always puts it there, so it is duplicated with the same value as the expanded array with readers
=> fix: fix collectors observability a bit

charts/kof-collectors/templates/opentelemetry/instrumentation.yaml
* Part of https://github.com/k0rdent/kof/issues/399
=> fix: Made `opentelemetry-go-instrumentation` path and version compatible with all image registries

charts/kof-collectors/values.yaml
- Fix invalid Prometheus URL to resolve `Prometheus communication error` on Mothership and regional clusters
=> fix: change Opencost prometheus URL to HTTP

charts/kof-mothership/templates/k0rdent/kof/svctmpl.yaml
* Thanks to @aglarendil for spotting this.
* Will cherry-pick to https://github.com/k0rdent/kof/tree/release/v1.2.0 after the merge.
* Should be included to KOF 1.2.1 patch release if we decide to make it.
=> fix: Added `ServiceTemplateChain` `cert-manager-v1-16-4-from-1-16-4` required for upgrade to KOF 1.2.0

charts/kof-mothership/files/dashboards/kubernetes-events/cluster-deployment-events.yaml, charts/kof-storage/files/dashboards/kubernetes-events/kubernetes-events-dashboard.yaml
* [From Management to Regional](https://docs.k0rdent.io/v1.2.0/admin/kof/kof-storing/#from-management-to-regional) case means:
metrics, logs, and traces from management cluster are sent to regional cluster.
* "Cluster Deployments Events" dashboard stopped supporting this case
after PR https://github.com/k0rdent/kof/pull/418
which added `/^logs$/` regex matching only `GrafanaDatasource` named exactly `logs` as in [From Management to Management](https://docs.k0rdent.io/v1.2.0/admin/kof/kof-storing/#from-management-to-management) case.
* That PR tried to fix the issue https://github.com/k0rdent/kof/issues/406
where selecting a regional datasource in this dashboard lead to `Status: 500`.
* Investigating this error deeper:
```
Status: 500. Message: error from datasource: ...
cannot parse query …
```
=> fix: "Cluster Deployments Events" dashboard vs "From Management to Regional" case

charts/kof-dashboards/files/dashboards/istio/istio-service-dashboard.yaml
* Internal Server Error:
```
[plugin.downstreamError] client: failed to query data:
json: cannot unmarshal string into Go struct field QueryModel.intervalFactor of type int64
```
* Tested after the fix, OK.
=> fix: Typo in `intervalFactor` lead to 500 in "Istio Service Dashboard"

charts/kof-collectors/values.yaml
Fix log level regex incorrectly matching codes
- Previously, regex would match lowercase strings like "f3781924612"
- Now only matches uppercase codes like "F8013", "E8321", etc.
- Made regex case-sensitive for EFDWI pattern matching
=> fix: incorrect log level parsing for uppercase codes

charts/kof-mothership/README.md, charts/kof-mothership/values.yaml, docs/system-requirements.md
- Increase memory `requests` and `limits` from 256Mi to 512Mi
- Update `System Requirements` docs to mention Promxy resource configuration
- Matching the correct memory resources is impossible due to varying queries and cluster counts
=> fix: prevent OOM crash in promxy on large queries

charts/kof-child/values.yaml, charts/kof-collectors/values.yaml, kof-operator/webapp/collector/src/components/features/DuplicateTargetsAlert.tsx, kof-operator/webapp/collector/src/components/features/TargetsList.tsx
Closes #227
- Add a check that detects duplicate Prometheus target scrape URLs
- Display misconfiguration error in the KOF UI
=> feat: add misconfiguration check for collector scrape in KOF UI

charts/kof-collectors/values.yaml, kof-operator/webapp/collector/src/components/features/SearchBar.tsx
Closes #411 
- Removed the `node-exporter` job from the daemon collector scrape config
- Added `node` and `nodename` labels to the `prometheus-node-exporter` ServiceMonitor so Grafana dashboards continue to render correctly.
- Dashboards related to Node Exporter metrics rendered correctly (tested on a regional cluster):
- Node Exporter Full
- KPS / Kubernetes / Compute Resources / Cluster
- KPS / Kubernetes / Compute Resources / Multi-Cluster
- KPS / Node Exporter / USE Method / Cluster
- KPS / Node Exporter / USE Method / Node
- KPS / Node Exporter / AIX
- KPS / Node Exporter / Nodes
- Dropped scraping of `kube-proxy` and `kube-dns` pods in the collector daemon scrape config (`kubernetes-pods` job) to prevent duplicate metrics on regional and child clusters.
- Dashboards related to …
=> fix: prevent duplicate metric collection

charts/kof-collectors/files/kube-state-metrics/custom-resources/k0rdent.yaml
These metrics are not in use in any dashboard
=> fix: remove timestamp metrics from kube-state custom resources

kof-operator/cmd/main.go, kof-operator/internal/server/handlers/cluster_deployments_handler.go, kof-operator/webapp/collector/.env.ci, kof-operator/webapp/collector/.env.development, kof-operator/webapp/collector/.env.production, kof-operator/webapp/collector/src/App.tsx, kof-operator/webapp/collector/src/components/features/AppSidebar.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/ClusterDeploymentLayout.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/components/details/ClusterDeploymentConfigTab.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/components/details/ClusterDeploymentDetails.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/components/details/ClusterDeploymentMetadataTab.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/components/details/ClusterDeploymentStatusTab.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/components/list/ClusterDeploymentList.tsx, kof-operator/webapp/collector/src/components/pages/clusterDeploymentsPage/models.ts, kof-operator/webapp/collector/src/components/shared/Loader.tsx, kof-operator/webapp/collector/src/components/shared/MetricsCard.tsx, kof-operator/webapp/collector/src/providers/cluster_deployments/ClusterDeploymentsProvider.tsx, kof-operator/webapp/collector/src/utils/formatter.ts
Part of #76 
This PR adds a page to the KOF UI that allows monitoring the health and configuration of cluster deployments.
=> feat: add cluster deployment monitoring page to KOF UI

charts/kof-child/Chart.yaml, charts/kof-collectors/Chart.yaml, charts/kof-dashboards/Chart.yaml, charts/kof-istio/Chart.yaml, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md, charts/kof-operators/Chart.yaml, charts/kof-operators/values.yaml, charts/kof-regional/Chart.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/Chart.yaml, charts/kof-storage/values.yaml
* There is a typo `grafana-operator.enables` (ends with "s") in 1.3.0 [kof-operators/values.yaml](https://github.com/k0rdent/kof/blob/v1.3.0/charts/kof-operators/values.yaml#L26),
while `grafana-operator.enabled` (ends with "d") is expected in [kof-operators/Chart.yaml](https://github.com/k0rdent/kof/blob/v1.3.0/charts/kof-operators/Chart.yaml#L10)
to determine if `grafana-operator` subchart should be installed.
* Despite this typo and expectation that non-existing field is falsy,
`grafana-operator` was still installed due to unexpected Helm docs [here](https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies:~:text=if%20no%20paths%20exist%20then%20the%20condition%20has%20no%20effect):
> if no paths exist then the condition has no effect.
* This PR fixes the typo …
=> fix: Typo `grafana-operator.enables/enabled`, dedup of this subchart, updated descriptions

charts/kof-collectors/values.yaml, charts/kof-dashboards/files/dashboards/kubernetes-events/kubernetes-events-dashboard.yaml, charts/kof-dashboards/files/dashboards/victoria-logs/victoria-logs.yaml
Closes https://github.com/k0rdent/kof/issues/372 and https://github.com/k0rdent/kof/issues/501
Flattening event fields allows victoria logs work with adhoc filters by removing the unnecessary transformations of metadata and regarding json fields in event log record
=> fix: flatten event fields for better filtering

Makefile, charts/kof-mothership/templates/promxy/promxyservergroup-crd.yaml
* Closes https://github.com/k0rdent/kof/issues/545
* The `--take-ownership` is required on upgrade to this version to avoid
`exists and cannot be imported into the current release: invalid ownership metadata`
* Will add it to release notes of KOF 1.4.0.
* Test:
```
kubectl get crd promxyservergroups.kof.k0rdent.mirantis.com -o yaml | yq .metadata
annotations:
controller-gen.kubebuilder.io/version: v0.16.1
helm.sh/resource-policy: keep
meta.helm.sh/release-name: kof-mothership
meta.helm.sh/release-namespace: kof
labels:
app.kubernetes.io/managed-by: Helm
...
```
=> fix: Auto-upgrade KOF CRD PromxyServerGroup

.github/workflows/build_images.yml, .github/workflows/release_images.yml, .goreleaser.yml, Makefile, charts/kof-child/values.yaml, charts/kof-collectors/values.yaml, charts/kof-istio/values.yaml, charts/kof-regional/values.yaml, docker/opentelemetry-collector-contrib/Dockerfile, docs/release.md, kof-operator/Makefile
Closes https://github.com/k0rdent/kof/issues/371
Enables [journaldreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/journaldreceiver) for daemon collector.
As the receiver requires journalctl binary a custom collector docker image is created with systemd package installed.
=> feat: add journald receiver to daemon collector

charts/kof-regional/templates/regional-multi-cluster-service.yaml, demo/cluster/adopted-cluster-regional.yaml
Closes https://github.com/k0rdent/kof/issues/459
=> fix: autodetect external dns credentials in regional MCS to enable it
