charts/motel-mothership/Chart.lock, charts/motel-mothership/Chart.yaml, charts/motel-mothership/values.yaml
Improving observability for core components
=> Add sveltos dashboard and cluster api visualizer helm charts

Makefile
Test:
```diff
--- aws-managed.yaml.old	2025-01-08 15:27:48
+++ aws-managed.yaml	2025-01-09 13:54:34
@@ -36,7 +36,7 @@
namespace: kof
values: |
global:
-          clusterName: aws-managed0
+          clusterName: dryzhkov-aws-managed
opencost:
enabled: true
opencost:
@@ -47,7 +47,7 @@
external:
url: "https://vmauth.dryzhkov-storage.project2a-dev.mirantis.com/vm/select/0/prometheus"
exporter:
-              defaultClusterId: "aws-managed0"
+              defaultClusterId: "dryzhkov-aws-managed"
kof:
logs:
credentials_secret_name: grafana-admin-credentials
```
=> Replace `aws-managed0` with `$(USER)-aws-managed`

Makefile, charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/templates/grafana/grafana.yaml, charts/kof-storage/values.yaml, demo/cluster/aws-eks-managed.yaml, demo/cluster/aws-eks-storage.yaml, demo/cluster/aws-standalone-managed.yaml, demo/cluster/aws-standalone-storage.yaml
=> Add eks demo templates

Makefile, charts/kof-mothership/files/dashboards/kcm-controller-manager.yaml, charts/kof-mothership/templates/kcm/service-monitor/kcm-controller-manager.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/templates/promxy/local-promxy-server-group.yaml, charts/kof-storage/values.yaml, docs/DEV.md
Closes #39, https://github.com/k0rdent/kcm/issues/869
=> Add mothership services monitoring and storage deployment option

.github/workflows/release_charts.yml, .github/workflows/release_operator.yml, Makefile, charts/kof-collectors/Chart.yaml, charts/kof-mothership/Chart.yaml, charts/kof-mothership/values.yaml, charts/kof-operators/Chart.yaml, charts/kof-storage/Chart.yaml, docs/DEV.md
=> Release charts under the same repo tag

Makefile, charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-mothership/templates/sveltos/grafana-dashboard.yaml, charts/kof-mothership/templates/sveltos/service-monitors.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/templates/grafana/datasources.yaml, charts/kof-storage/templates/grafana/grafana.yaml, charts/kof-storage/templates/promxy/local-promxy-server-group.yaml, demo/cluster/aws-eks-storage.yaml, demo/cluster/aws-standalone-storage.yaml, docs/DEV.md
Closes https://github.com/k0rdent/kof/issues/43
Closes https://github.com/k0rdent/kof/issues/30
Closes https://github.com/k0rdent/kof/issues/23
=> k0rdent monitoring improvements

charts/kof-mothership/templates/k0rdent/catalog/helm-repo.yaml
Related to https://github.com/k0rdent/kof/pull/52
=> Add k0rdent-catalog helm repo to kof

charts/kof-collectors/templates/opentelemetry/node-collector.yaml
=> Better logs parsing and labeling

charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-storage/templates/grafana/grafana.yaml
=> Add grafana plugins for VictoriaMetrics datasources

charts/kof-mothership/templates/k0rdent/kof/svctmpl.yaml, demo/cluster/aws-eks-managed.yaml, demo/cluster/aws-eks-storage.yaml, demo/cluster/aws-standalone-managed.yaml, demo/cluster/aws-standalone-storage.yaml
All service templates are immutable and should be versioned.
Part of https://github.com/k0rdent/kof/issues/60
=> Versioned service templates of kof charts

charts/kof-storage/values.yaml, demo/cluster/aws-eks-regional.yaml, docs/DEV.md
* Valuable changes extracted from closed PR https://github.com/k0rdent/kof/pull/123
* Part of https://github.com/k0rdent/kof/issues/70
=> Adopted local cluster, fix of `victoria-logs-single` values, and of `make dev-ms-deploy`

charts/kof-collectors/templates/opentelemetry/node-collector.yaml, charts/kof-istio/values.yaml, charts/kof-mothership/files/dashboards/istio-contral-plane-dashboad.yaml, charts/kof-mothership/files/dashboards/istio-mesh-dashboard.yaml, charts/kof-mothership/files/dashboards/istio-performance-dashboard.yaml, charts/kof-mothership/files/dashboards/istio-service-dashboard.yaml, charts/kof-mothership/files/dashboards/istio-wasm-extension-dashboard.yaml, charts/kof-mothership/files/dashboards/istio-workload-dashboard.yaml, charts/kof-storage/files/dashboards/istio-contral-plane-dashboad.yaml, charts/kof-storage/files/dashboards/istio-mesh-dashboard.yaml, charts/kof-storage/files/dashboards/istio-performance-dashboard.yaml, charts/kof-storage/files/dashboards/istio-service-dashboard.yaml, charts/kof-storage/files/dashboards/istio-wasm-extension-dashboard.yaml, charts/kof-storage/files/dashboards/istio-workload-dashboard.yaml
Closes https://github.com/k0rdent/kof/issues/95
=> Add Grafana dashboards for Istio metrics monitoring

docs/DEV.md
=> Mentioned helm docs hook in docs/DEV.md

docs/DEV.md, docs/istio.md
Closes https://github.com/k0rdent/kof/issues/152
=> Add istio documentation

.github/workflows/pr_test_helm_chart.yml, Makefile, charts/kof-istio/templates/kof-child-cluster-profile.yaml, charts/kof-istio/templates/telemetry.yaml, charts/kof-istio/values.yaml, charts/kof-mothership/README.md, charts/kof-mothership/values.yaml, charts/kof-storage/templates/jaeger/jaeger.yaml, docs/DEV.md
* Contains latest cherry-picks blocking the release.
* I'll create pre-release and tag after merging this PR.
=> Part 2 of kof v0.2.0-rc1

.github/workflows/release_charts.yml, docs/DEV.md
Fix of https://github.com/k0rdent/kof/actions/runs/14064671721/job/39384002088#step:6:35
=> v0.2.0-rc1-part3: Fixed .github/workflows/release_charts.yml

kof-operator/internal/controller/promxyservergroup_controller_test.go, kof-operator/internal/controller/secret_test.go, kof-operator/internal/controller/template/secret.tmpl
Closes https://github.com/k0rdent/kof/issues/89
=> Fix promxy datasource

charts/kof-mothership/templates/k0rdent/kof/helm-repo.yaml
our kof HelmRepo is a fluxcd object. let's just leave it that way and pass all the fields that the user specified
=> pass HelmRepo object completely instead of picking the fields

.github/workflows/pr_test_upgrade.yml
Fixing `no space left on device` issue with CI job
=> ci: add disk cleanup and docker cache

Makefile, charts/kof-collectors/templates/kcm/pod-monitor/control-plane.yaml, charts/kof-collectors/templates/kcm/service-monitor/kcm-controller-manager.yaml, charts/kof-collectors/templates/opentelemetry/clusterroles/node-exporter-ta.yaml, charts/kof-collectors/templates/opentelemetry/node-collector.yaml, charts/kof-collectors/templates/opentelemetry/serviceaccounts/k8s-cluster-collector-token.yaml, charts/kof-collectors/values.yaml, charts/kof-operators/values.yaml
Part of  https://github.com/k0rdent/kof/issues/241
=> feat: add control plane monitoring with otel mtls setup

charts/kof-mothership/README.md, charts/kof-mothership/templates/grafana/grafana.yaml, charts/kof-mothership/values.yaml, charts/kof-storage/templates/victoria/vmcluster.yaml, charts/kof-storage/values.yaml
closes https://github.com/k0rdent/kof/issues/261
=> feat: extend resources customization for grafana and vmcluster

Makefile, charts/kof-collectors/values.yaml, charts/kof-istio/templates/_helpers.tpl, charts/kof-istio/templates/kof-regional-cluster-profile.yaml, charts/kof-regional/templates/regional-multi-cluster-service.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/Chart.yaml, charts/kof-storage/templates/istio/istio-vm-services.yaml, charts/kof-storage/templates/victoria/vmuser.yaml, charts/kof-storage/values.yaml, demo/cluster/aws-eks-regional.yaml, demo/cluster/aws-standalone-child.yaml, demo/cluster/aws-standalone-regional.yaml, demo/cluster/azure-standalone-regional.yaml, docs/collect-from-management.md, docs/system-requirements.md, kof-operator/internal/controller/clusterdeployment_controller_test.go, kof-operator/internal/controller/clusterdeployment_kof_cluster_role.go
Close https://github.com/k0rdent/kof/issues/182
Run victoria logs cluster instead of viactoria logs single, without any data migration
=> feat: move to victoria-log-cluster

charts/kof-storage/templates/victoria/vmalert.yaml, charts/kof-storage/templates/victoria/vmcluster.yaml, charts/kof-storage/values.yaml
closes #261
misc: fix replicationFactor keys location as well
=> fix: support modification of resources for all VM services

.github/workflows/pr_test_upgrade.yml, Makefile, demo/cluster/adopted-cluster-child.yaml, demo/cluster/adopted-cluster-regional.yaml, docs/DEV.md, scripts/patch-coredns.bash, scripts/wait-helm-charts.bash
Closes https://github.com/k0rdent/kof/issues/254
=> test: add adopted child cluster deployment

charts/kof-collectors/templates/_helpers.tpl, charts/kof-collectors/templates/opentelemetry/node-collector.yaml, charts/kof-collectors/values.yaml, charts/kof-mothership/files/dashboards/cluster-deployment-events.yaml, charts/kof-storage/files/dashboards/victoria-logs.yaml
=> feat: Add cluster filter to Victoria Logs dashboard

docs/collection-recipes.md
Closes https://github.com/k0rdent/kof/issues/176
Closes https://github.com/k0rdent/kof/issues/177
=> docs: add data sending customization recipe

charts/kof-mothership/Chart.lock, charts/kof-mothership/Chart.yaml, charts/kof-mothership/README.md, charts/kof-mothership/values.yaml
* Fixes https://github.com/k0rdent/kof/issues/388
* The new [kgst-1.0.0](https://github.com/k0rdent/catalog/tree/main/apps/k0rdent-utils/charts/kgst-1.0.0) adds verification with breaking changes to its values interface.
* Related: https://github.com/k0rdent/catalog/pull/489
=> chore: Use kgst 1.0.0

charts/kof-mothership/README.md, charts/kof-mothership/values.yaml
Closes https://github.com/k0rdent/kof/issues/405
=> fix: change cluster filter label in dashboards

charts/kof-storage/files/dashboards/victoria-logs-cluster.yaml, charts/kof-storage/files/dashboards/victoria-metrics-cluster.yaml, charts/kof-storage/files/dashboards/victoria-metrics-operator.yaml
Similar to https://github.com/k0rdent/kof/issues/405
=> fix: add cluster filter for Victoria logs/metrics Grafana dashboards

charts/kof-istio/templates/_helpers.tpl
this collector should be called controller-k0s
=> fix: fix typo on helpers.tpl

charts/kof-child/values.yaml, charts/kof-collectors/values.yaml
=> fix: fix collection of metrics from otel collectors

charts/kof-child/templates/child-multi-cluster-service.yaml, demo/cluster/adopted-cluster-child.yaml
Closes https://github.com/k0rdent/kof/issues/413
=> fix: read vmauth credentials from secret

.github/workflows/pr_test_helm_chart.yml, .github/workflows/pr_test_upgrade.yml, .github/workflows/release_operator.yml, Makefile, charts/kof-mothership/templates/promxy/_helpers.tpl, demo/cluster/adopted-cluster-regional.yaml, docs/dev.md, scripts/metrics.py, scripts/patch-coredns.bash, scripts/requirements.txt
Closing https://github.com/k0rdent/kof/issues/400
Checking in CI that metrics are actually collected for adopted child and regional clusters
=> test: checking promxy metrics collection

charts/kof-mothership/Chart.lock, charts/kof-mothership/README.md, charts/kof-mothership/templates/_helpers.tpl, charts/kof-mothership/templates/victoria/vmalert.yaml, charts/kof-mothership/templates/victoria/vmalertmanager.yaml, charts/kof-mothership/templates/victoria/vmcluster.yaml, charts/kof-mothership/values.yaml, charts/kof-regional/templates/regional-multi-cluster-service.yaml, charts/kof-storage/Chart.lock, charts/kof-storage/templates/victoria/vmalert.yaml, charts/kof-storage/templates/victoria/vmauth.yaml, charts/kof-storage/templates/victoria/vmcluster.yaml, charts/kof-storage/values.yaml
Close https://github.com/k0rdent/kof/issues/338
=> feat: allow full vm custom objects specs definition in values

.github/workflows/pr_test_upgrade.yml
Closes https://github.com/k0rdent/kof/issues/360
=> ci: checkout latest KCM main for upgrade test

charts/kof-collectors/templates/opentelemetry/clusterrolebindings/daemon.yaml, charts/kof-collectors/values.yaml
More info about the feature https://opentelemetry.io/blog/2025/otel-collector-k8s-discovery/
Closes: https://github.com/k0rdent/kof/issues/516
=> feat: migrate to receiver_creator for filelog/containers to support annotation-based discovery

kof-operator/webapp/collector/package-lock.json, kof-operator/webapp/collector/package.json
* Closes https://github.com/k0rdent/kof/security/dependabot/26 and https://github.com/k0rdent/kof/security/dependabot/27
=> fix: Security fix of vite

kof-operator/internal/controller/istio/remote-secret/remote_secret.go, kof-operator/internal/controller/istio/remote-secret/remote_secret_test.go
Close: https://github.com/k0rdent/kof/issues/393
=> fix: shorten profile name to fit in 63 characters limitation
